# Generated by Django 4.2.6 on 2023-11-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instakilogram_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_users',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
