# Generated by Django 4.2.6 on 2023-11-07 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insta_users',
            fields=[
                ('username', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('imgThumb', models.ImageField(blank=True, null=True, upload_to='media_img')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('imgThumb', models.ImageField(blank=True, null=True, upload_to='media_img')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instakilogram_web.insta_users')),
            ],
        ),
    ]
