# Generated by Django 4.2.6 on 2023-10-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instakilogram_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='reel',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
