# Generated by Django 4.2.6 on 2023-10-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instakilogram_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
    ]
